#!/bin/sh
# 
# file: .git/hook/pre-commit
#

. libs/githooks/shellcheck-precommit.sh
#. githooks/detect-secret-pre-commit.sh

#. /home/azureuser/COF/libs/githooks/pre-commit



#. libs/githooks/pre-commit